apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: vcluster-flux-demo-kargo
  namespace: p-vcluster-flux-demo
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  interval: 5m0s
  url: 'https://github.com/loft-demos/test-env-app.git'
  ref:
    branch: 'main'
