apiVersion: v1
kind: Secret
metadata:
  name: argo-appset-webhook-url
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  url: "https://argocd-appset-test-env.us.demo.dev/api/webhook"
