apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pr-vcluster-multi-k8s
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - k8sVersion: v1.33.3
                  k8sVersionDNSLabel: 1-33-3
                - k8sVersion: v1.32.7
                  k8sVersionDNSLabel: 1-32-7
          - pullRequest:
              gitea:
                owner: loft-demos
                repo: test-env-app
                api: "https://github.com"
                tokenRef:
                  secretName: loft-demo-org-cred
                  key: token
              requeueAfterSeconds: 86400
              template:
                metadata: {}
                spec:
                  destination: {}
                  project: ''
  template:
    spec:
      info:
        - name: PR vCluster Argo CD URL
          value: https://argocd-test-env-app.us.demo.dev
        - name: Pull Request
          value: 'https://github.com/loft-demos/test-env-app/pulls/{{number}}'
      source:
        repoURL: 'https://github.com/loft-demos/test-env-app.git'
